#!/usr/bin/env python3
"""Generate the moc3 section table from PurismCore's moc3.h.

The section order in a .moc3 file is exactly the order of the D()/S() entries
in the PSM__SECTIONS_V** macros, concatenated by version. Deriving the table
from that header instead of hand-maintaining it is what makes the writer
correct by construction -- and it is the only place the v4.2/v5.0/v5.3
sections are documented at all.

Usage:  python3 tools/gen_layout.py path/to/purism/src/moc3.h > src/moc3/_layout.py
"""
from __future__ import annotations

import re
import sys

# psm__ C type -> our element type name. RUNTIME entries are pointer slots that
# the runtime fills in; on disk they are zero-filled padding of 4 or 8 bytes.
TYPE_MAP = {
    "psm__i32": "I32",
    "psm__f32": "F32",
    "psm__u16": "U16",
    "psm__u8": "U8",
    "struct psm__id": "STR64",
    "const char *": "RUNTIME_PTR",
    "const psm__f32 *": "RUNTIME_PTR",
    "const psm__i32 *": "RUNTIME_PTR",
    "const psm__u16 *": "RUNTIME_PTR",
    "const psm__u8 *": "RUNTIME_PTR",
    "const struct psm__id *": "RUNTIME_PTR",
}

VERSION_OF_GROUP = {"V30": 1, "V33": 2, "V42": 4, "V50": 5, "V53": 6}

GROUP_RE = re.compile(r"#define PSM__SECTIONS_(V\d+)\(S, D\) \\\n((?:.*\\\n)*.*)")
ENTRY_RE = re.compile(r"^\s*([SD])\(\s*(.+?)\s*,\s*([\w.]+)\s*,\s*(\w+)\s*\)")


def parse_counts(header: str) -> list[str]:
    m = re.search(r"struct psm__count_info \{(.*?)\};", header, re.S)
    if not m:
        raise SystemExit("count_info struct not found")
    return re.findall(r"psm__i32\s+(\w+);", m.group(1))


def parse_groups(header: str) -> list[tuple[str, list[tuple[str, str, str, str]]]]:
    groups = []
    for gm in GROUP_RE.finditer(header):
        name, body = gm.group(1), gm.group(2)
        entries = []
        for line in body.split("\n"):
            em = ENTRY_RE.match(line)
            if em:
                entries.append(em.groups())  # kind, ctype, member, count
        groups.append((name, entries))
    return groups


def main() -> None:
    header = open(sys.argv[1]).read()
    counts = parse_counts(header)
    groups = parse_groups(header)

    out: list[str] = []
    out.append('"""Generated by tools/gen_layout.py from PurismCore moc3.h. Do not edit."""')
    out.append("")
    out.append("# count_info field order -- index into Moc3.counts")
    out.append("COUNT_FIELDS = [")
    for c in counts:
        out.append(f"    {c!r},")
    out.append("]")
    out.append("COUNT_IDX = {name: i for i, name in enumerate(COUNT_FIELDS)}")
    out.append("")
    out.append("# (name, elem_type, count_field, min_version)")
    out.append("# count_field None means a fixed-size struct handled separately.")
    out.append("SECTIONS = [")

    total = 0
    for gname, entries in groups:
        ver = VERSION_OF_GROUP[gname]
        out.append(f"    # --- {gname} (version >= {ver}) ---")
        for kind, ctype, member, count in entries:
            if kind == "S":
                # count_info / canvas_info: fixed structs, written by hand
                out.append(f"    ({member!r}, 'STRUCT', None, {ver}),")
                total += 1
                continue
            et = TYPE_MAP.get(ctype)
            if et is None:
                raise SystemExit(f"unmapped C type: {ctype!r} ({member})")
            if count not in counts:
                raise SystemExit(f"unknown count field: {count!r} ({member})")
            out.append(f"    ({member!r}, {et!r}, {count!r}, {ver}),")
            total += 1
    out.append("]")
    out.append("")
    out.append(f"# {total} sections total")

    print("\n".join(out))
    print(f"# groups: {', '.join(g for g, _ in groups)}", file=sys.stderr)
    print(f"# sections: {total}", file=sys.stderr)


if __name__ == "__main__":
    main()
